- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install the latest version of mongodb 
  ansible.builtin.dnf:
    name: mongodb-org
    state: present 

- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: update lisen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf 
  #ansible.builtin.command: sed -i "s/127.0.0.1/0.0.0.0/g" /etc/mongod.conf 
  ansible.builtin.replace: 
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted
 