- name: "{{component}} app setup"
  ansible.builtin.import_role: 
    name: common 
    tasks_from: app-setup

- name: installing python 
  ansible.builtin.import_role: 
    name: common 
    tasks_from: python

- name: "{{component}} service start and stop"
  ansible.builtin.import_role: 
    name: common 
    tasks_from: systemd
