- name: copy mongo.repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo 

- name: install mongodb-org-shell
  ansible.builtin.dnf: 
    name: mongodb-org-shell
    state: present 

- name: get the categories count 
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

- name: get the categories count 
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "entries count: {{entries_count}}"

- name: "load catalogue data"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "catalogue" and products_count.stdout == "0"  # keep double quotes
  #ignore_errors: true

- name: "load user data"
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js"
  when: component == "user" and users_count.stdout == "0"  # keep double quotes
  #ignore_errors: true