- name: disable old nodejs and enable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: enable nodejs
  ansible.builtin.dnf: 
    name: nodejs
    state: present 

- name: download dependencies 
  ansible.builtin.command: npm install 
  args: 
    chdir: /app 
