- name: install python 
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present 
  loop: 
    - python36 
    - gcc 
    - python3-devel

- name: install requirements 
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args: 
    chdir: /app 