- name: "copy {{component}} service in systemd"
  ansible.builtin.copy: 
    src: "{{component}}.service.j2"
    dest: /etc/systemd/system/"{{component}}.service"

- name: sytemctl daemon reload 
  ansible.builtin.systemd_service:
    daemon_reload: true 

- name: start and enable 
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes 