- name: app installation 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: nodejs installtion 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs 

- name: start and enable service 
  ansible.builtin.import_role: 
    name: common 
    tasks_from: systemd 





